version: "3.9"

services:
  # MinIO (S3 compatible object storage)
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # n8n automation with Postgres
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: n8n-postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8npass
      GENERIC_TIMEZONE: Europe/Berlin
    depends_on:
      - n8n-postgres

  n8n-postgres:
    image: postgres:17-alpine
    container_name: n8n-postgres
    restart: always
    environment:
      POSTGRES_DB: n8n
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8npass
    volumes:
      - n8n_pgdata:/var/lib/postgresql/data

  # NocoDB with its Postgres
  nocodb:
    image: nocodb/nocodb:latest
    container_name: nocodb
    ports:
      - "8080:8080"
    environment:
      NC_DB: "pg://nocodb-postgres:5432?u=nocodb&p=nocodbpass&d=nocodb"
      NC_ALLOW_LOCAL_HOOKS: "true"
    depends_on:
      - nocodb-postgres

  nocodb-postgres:
    image: postgres:17-alpine
    container_name: nocodb-postgres
    restart: always
    environment:
      POSTGRES_DB: nocodb
      POSTGRES_USER: nocodb
      POSTGRES_PASSWORD: nocodbpass
    volumes:
      - nocodb_pgdata:/var/lib/postgresql/data

  # Postgres for AI agents memorization
  agents-postgres:
    image: postgres:17-alpine
    container_name: agents-postgres
    restart: always
    environment:
      POSTGRES_DB: agents_memory
      POSTGRES_USER: agents
      POSTGRES_PASSWORD: agentspass
    ports:
      - "5434:5432"
    volumes:
      - agents_pgdata:/var/lib/postgresql/data

  # Maildev for mail development
  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1080:1080" # Web UI
      - "1025:1025" # SMTP
    restart: always

  # Meilisearch
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    environment:
      - MEILI_NO_ANALYTICS=true
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data

volumes:
  minio_data:
  n8n_pgdata:
  nocodb_pgdata:
  agents_pgdata:
  meili_data:
